### ISSUE TITLE
Feature request: support lowercase lookup

### ISSUE THREAD

**Issue by pantaoran** [tstuber/IptChomeExtension#1]
Finde diese Extension als neuer Mitarbeiter sehr nützlich, da ich so gut wie keine Kürzel kenne!

Vielleicht wäre es schön wenn man beim manuellen Lookup die Gross/Kleinschreibung ignorieren könnte. Im Moment scheint das nur mit Grossbuchstaben zu funktionieren.

**Comment by tstuber** [comment]
Danke für den Input :) Bei mir funktioniert es auch mit Kleinschreibung, jedoch wird bei der Eingabe vom Kürzel nicht automatisch die Details angezeigt. Die Listeneinträge würde ich aber grundsätzlich sehen. Hast du das gemeint? Oder verhält es sich bei dir anders?

**Comment by pantaoran** [comment]
Ich glaube ja. Nach dem Tippen von "tst" passiert noch nichts, und auch Enter drücken hilft nicht, aber wenn ich dann den Pfeil am rechten Rand des Eingabefeldes mit der Maus klicke, dann wird das Resultat angezeigt.

Mit Grossbuchstaben erscheint das Resultat, sobald ich den dritten Buchstaben getippt habe. Ich möchte das Gleiche für lower case.

**Comment by tstuber** [comment]
Alles klar, das sollte gefixt sein. Beim nächsten Google Autoupdate sollte die Änderung übernommen werden.
